import { loader } from 'fumadocs-core/source';
import { docs } from '../.source/index';

/**
 * Content index generated by fumadocs-mdx.
 *
 * `next.config.mjs` is what makes fumadocs emit the webpack-compatible index
 * under .source/ instead of a Vite `import.meta.glob` call, and createMDX there
 * registers the MDX loader webpack needs for the `?collection=` imports.
 *
 * The generated module is excluded from typecheck (it is emitted code built
 * against a newer fumadocs-core than the one installed here), so it is adapted
 * through the `toFumadocsSource()` helper the generator provides rather than
 * through the raw collection shape.
 */
export const source = loader({
  baseUrl: '/',
  source: (docs as unknown as { toFumadocsSource: () => unknown }).toFumadocsSource() as Parameters<
    typeof loader
  >[0]['source'],
});